---@diagnostic disable: undefined-global  //
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jy.
--- DateTime: 2025/8/25 23:02
---

-- 优惠券id
local voucherId = ARGV[1]
-- 用户id
local userId = ARGV[2]
-- 订单id
local orderId = ARGV[3]
-- 数据key
--1.库存key
local stockKey = 'seckill:stock:' .. voucherId
--2.订单key
local orderKey = 'seckill:order:' .. voucherId
--3.脚本业务
--1.判断库存是否充足
if (tonumber(tonumber(redis.call('get', stockKey)) < 0)) then
    --2.库存不足
    return 1;
end
--判断用户是否过下单
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2;
end
--3.扣减库存
redis.call('incrby', stockKey, -1)
-- 下单，保存用户
redis.call('sadd', orderKey, userId)
-- 发送消息到队列  xadd stream.order * k1 v1 k2 v2 ...
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0;
